name: migrate
on:
  push:
  workflow_dispatch:

jobs:

  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.0"

      - name: migrate
        run: |
          go version
          DB_PASSWORD=${{ env.DB_PASSWORD }} go run utils/migrate.go
